# Generated by Django 2.1 on 2018-08-29 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('youtube_id', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True, verbose_name='Youtube ID')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('thumbnail_url', models.CharField(max_length=256, verbose_name='Thumbnail Link')),
                ('published_at', models.DateTimeField(verbose_name='Published At')),
            ],
            options={
                'verbose_name': 'Video Item',
                'verbose_name_plural': 'Video Items',
                'ordering': ('created_at',),
            },
        ),
        migrations.AlterField(
            model_name='keyword',
            name='name',
            field=models.CharField(max_length=256, unique=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='videoitem',
            name='keywords',
            field=models.ManyToManyField(related_name='videos', to='keywords.Keyword'),
        ),
    ]
