version: '3'
services:
  redis:
    image: 'redis:alpine'
  web:
    build: ./
    ports:
      - 8000:8000
    restart: on-failure
    links:
      - redis
    env_file:
      - .env
    volumes:
      - ./src/:/app
    command: bash -c 'cd /app && python manage.py migrate && python manage.py runserver 0:8000'
  celery:
    build: ./
    depends_on:
      - redis
    restart: on-failure
    links:
      - redis
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/1
    volumes:
      - ./src/:/app
    command: bash -c 'cd /app && celery -A celery_app worker -l INFO -Q default --beat'
